#!/bin/bash

# Quick script to create test edges via Strapi Admin

echo "🔗 Creating Knowledge Edges via Strapi Admin Panel..."
echo ""
echo "Otwórz: http://localhost:1337/admin"
echo ""
echo "1. Przejdź do: Content Manager → Knowledge Edge"
echo "2. Kliknij: Create new entry"
echo "3. Dodaj przykładowe edges:"
echo ""
echo "   Edge 1:"
echo "   - Source Article: ID 1 (KSeF 2026: Kompletny Przewodnik)"
echo "   - Target Article: ID 3 (Jak obliczyć koszt wdrożenia)"
echo "   - Relationship Type: BUILDS_ON"
echo "   - Weight: 0.9"
echo "   - Anchor Text: 'Sprawdź koszty wdrożenia'"
echo ""
echo "   Edge 2:"
echo "   - Source Article: ID 1"
echo "   - Target Article: ID 5 (10 najczęstszych błędów)"
echo "   - Relationship Type: RELATED_TO"
echo "   - Weight: 0.8"
echo "   - Anchor Text: 'Uniknij częstych błędów'"
echo ""
echo "   Edge 3:"
echo "   - Source Article: ID 3"
echo "   - Target Article: ID 7 (KSeF API)"
echo "   - Relationship Type: PREREQUISITE"
echo "   - Weight: 0.75"
echo "   - Anchor Text: 'Techniczne aspekty integracji'"
echo ""
echo "4. Po dodaniu edges, uruchom:"
echo "   curl -X POST http://localhost:1337/api/graph/run-analysis"
echo ""
echo "5. Sprawdź wyniki:"
echo "   curl http://localhost:1337/api/graph/stats | python3 -m json.tool"
echo ""
