import type { Article } from "./types"

export const mockArticles: Article[] = [
  {
    id: "1",
    slug: "ksef-2026-kompletny-przewodnik",
    title: "KSeF 2026: Kompletny Przewodnik dla Firm",
    excerpt:
      "Wszystko co musisz wiedzieć o obowiązkowym wdrożeniu KSeF od 1 lutego 2026. Terminy, koszty, kary i proces wdrożenia krok po kroku.",
    thumbnail: "/modern-office-with-digital-invoicing-system.jpg",
    category: "Podstawy",
    tags: ["termin wdrożenia", "obowiązek", "przewodnik"],
    difficulty: "Podstawowy",
    contentType: "Przewodnik",
    author: {
      name: "Jan Kowalski",
      avatar: "/professional-male-consultant.jpg",
      role: "Certyfikowany Konsultant KSeF",
      bio: "Ekspert z 15-letnim doświadczeniem w automatyzacji procesów księgowych. Pomógł 200+ firmom wdrożyć systemy e-fakturowania.",
    },
    publishedAt: "2025-10-15T09:00:00Z",
    updatedAt: "2025-10-25T14:30:00Z",
    readingTime: 15,
    views: 12453,
    commentsCount: 18,
    rating: {
      average: 4.9,
      count: 234,
    },
    isFeatured: true,
    isTrending: true,
    isUpdated: true,
    isBookmarked: false,
    hasCTA: true,
    ctaText: "Zobacz kalkulator",
    ctaAction: "calculator",
  },
  {
    id: "2",
    slug: "jak-obliczyc-koszt-wdrozenia-ksef",
    title: "Jak obliczyć koszt wdrożenia KSeF w 2026?",
    excerpt:
      "Szczegółowy przewodnik po kosztach wdrożenia dla różnych wielkości firm. Kalkulator kosztów i porównanie dostawców.",
    thumbnail: "/calculator-and-financial-charts.jpg",
    category: "Koszty",
    tags: ["koszty", "kalkulator", "wdrożenie"],
    difficulty: "Średni",
    contentType: "Artykuł",
    author: {
      name: "Anna Nowak",
      avatar: "/professional-female-accountant.png",
      role: "Ekspert ds. Finansów",
      bio: "Specjalistka z 12-letnim doświadczeniem w optymalizacji kosztów IT dla firm.",
    },
    publishedAt: "2025-10-20T10:00:00Z",
    updatedAt: "2025-10-26T09:00:00Z",
    readingTime: 12,
    views: 8234,
    commentsCount: 24,
    rating: {
      average: 4.8,
      count: 156,
    },
    isFeatured: true,
    isTrending: true,
    isUpdated: true,
    isBookmarked: false,
    hasCTA: true,
    ctaText: "Użyj kalkulatora",
    ctaAction: "calculator",
  },
  {
    id: "3",
    slug: "10-najczestszych-bledow-wdrozenie-ksef",
    title: "10 najczęstszych błędów przy wdrożeniu KSeF",
    excerpt: "Poznaj pułapki, które mogą kosztować Twoją firmę tysiące złotych i dowiedz się, jak ich uniknąć.",
    thumbnail: "/warning-signs-and-business-mistakes.jpg",
    category: "Wdrożenie",
    tags: ["błędy", "najlepsze praktyki", "wdrożenie"],
    difficulty: "Średni",
    contentType: "Artykuł",
    author: {
      name: "Piotr Wiśniewski",
      avatar: "/professional-male-it-consultant.jpg",
      role: "Architekt Systemów IT",
      bio: "Specjalista z 18-letnim doświadczeniem w integracji systemów księgowych.",
    },
    publishedAt: "2025-10-18T14:00:00Z",
    updatedAt: "2025-10-18T14:00:00Z",
    readingTime: 10,
    views: 6543,
    commentsCount: 15,
    rating: {
      average: 4.7,
      count: 98,
    },
    isFeatured: true,
    isTrending: false,
    isUpdated: false,
    isBookmarked: false,
    hasCTA: false,
  },
  {
    id: "4",
    slug: "ksef-api-dokumentacja-integracja",
    title: "KSeF API: Kompletna dokumentacja integracji",
    excerpt: "Techniczny przewodnik po API KSeF z przykładami kodu i najlepszymi praktykami integracji.",
    thumbnail: "/api-code-and-programming.jpg",
    category: "Techniczne",
    tags: ["API", "integracja", "programowanie"],
    difficulty: "Zaawansowany",
    contentType: "Przewodnik",
    author: {
      name: "Marek Kowalczyk",
      avatar: "/professional-male-developer.jpg",
      role: "Senior Developer",
      bio: "Full-stack developer z 10-letnim doświadczeniem w integracji systemów fiskalnych.",
    },
    publishedAt: "2025-10-22T11:00:00Z",
    updatedAt: "2025-10-27T16:00:00Z",
    readingTime: 25,
    views: 4521,
    commentsCount: 32,
    rating: {
      average: 4.9,
      count: 87,
    },
    isFeatured: false,
    isTrending: true,
    isUpdated: true,
    isBookmarked: false,
    hasCTA: true,
    ctaText: "Zobacz przykłady",
    ctaAction: "examples",
  },
  {
    id: "5",
    slug: "kary-za-brak-wdrozenia-ksef",
    title: "Kary za brak wdrożenia KSeF - ile zapłacisz?",
    excerpt:
      "Szczegółowe zestawienie kar i sankcji za niewdrożenie KSeF w terminie. Aktualne przepisy i interpretacje.",
    thumbnail: "/legal-documents-and-penalties.jpg",
    category: "Prawo",
    tags: ["kary", "prawo", "sankcje"],
    difficulty: "Podstawowy",
    contentType: "Artykuł",
    author: {
      name: "Dr Katarzyna Lewandowska",
      avatar: "/professional-female-lawyer.png",
      role: "Radca Prawny",
      bio: "Specjalistka prawa podatkowego z 20-letnim doświadczeniem.",
    },
    publishedAt: "2025-10-19T09:00:00Z",
    updatedAt: "2025-10-19T09:00:00Z",
    readingTime: 8,
    views: 9876,
    commentsCount: 21,
    rating: {
      average: 4.6,
      count: 145,
    },
    isFeatured: false,
    isTrending: true,
    isUpdated: false,
    isBookmarked: false,
    hasCTA: false,
  },
  {
    id: "6",
    slug: "ksef-dla-mikrofirm-przewodnik",
    title: "KSeF dla mikrofirm - uproszczony przewodnik",
    excerpt:
      "Wszystko co musisz wiedzieć o KSeF, jeśli prowadzisz małą firmę. Proste wyjaśnienia bez zbędnego żargonu.",
    thumbnail: "/small-business-owner-with-laptop.jpg",
    category: "Podstawy",
    tags: ["mikrofirma", "przewodnik", "podstawy"],
    difficulty: "Podstawowy",
    contentType: "Przewodnik",
    author: {
      name: "Tomasz Zieliński",
      avatar: "/friendly-male-business-consultant.jpg",
      role: "Doradca dla MŚP",
      bio: "Pomaga małym firmom w cyfrowej transformacji od 8 lat.",
    },
    publishedAt: "2025-10-21T10:00:00Z",
    updatedAt: "2025-10-21T10:00:00Z",
    readingTime: 7,
    views: 5432,
    commentsCount: 12,
    rating: {
      average: 4.8,
      count: 76,
    },
    isFeatured: false,
    isTrending: false,
    isUpdated: false,
    isBookmarked: false,
    hasCTA: false,
  },
  {
    id: "7",
    slug: "porownanie-dostawcow-oprogramowania-ksef",
    title: "Porównanie dostawców oprogramowania KSeF 2026",
    excerpt: "Szczegółowe porównanie 15 najpopularniejszych systemów KSeF. Ceny, funkcje, opinie użytkowników.",
    thumbnail: "/software-comparison-chart.jpg",
    category: "Wdrożenie",
    tags: ["porównanie", "oprogramowanie", "dostawcy"],
    difficulty: "Średni",
    contentType: "Artykuł",
    author: {
      name: "Agnieszka Dąbrowska",
      avatar: "/professional-female-analyst.jpg",
      role: "Analityk IT",
      bio: "Specjalistka od analizy i porównywania rozwiązań IT dla biznesu.",
    },
    publishedAt: "2025-10-23T13:00:00Z",
    updatedAt: "2025-10-28T10:00:00Z",
    readingTime: 18,
    views: 7654,
    commentsCount: 28,
    rating: {
      average: 4.7,
      count: 112,
    },
    isFeatured: false,
    isTrending: true,
    isUpdated: true,
    isBookmarked: false,
    hasCTA: true,
    ctaText: "Zobacz ranking",
    ctaAction: "ranking",
  },
  {
    id: "8",
    slug: "ksef-faq-najczesciej-zadawane-pytania",
    title: "KSeF FAQ - 50 najczęściej zadawanych pytań",
    excerpt: "Odpowiedzi na wszystkie pytania dotyczące KSeF. Aktualizowane na bieżąco przez ekspertów.",
    thumbnail: "/question-marks-and-answers.jpg",
    category: "Podstawy",
    tags: ["FAQ", "pytania", "odpowiedzi"],
    difficulty: "Podstawowy",
    contentType: "FAQ",
    author: {
      name: "Zespół KSeF Portal",
      avatar: "/team-of-experts.jpg",
      role: "Redakcja",
      bio: "Zespół ekspertów ds. KSeF i e-fakturowania.",
    },
    publishedAt: "2025-10-10T08:00:00Z",
    updatedAt: "2025-10-28T15:00:00Z",
    readingTime: 20,
    views: 15234,
    commentsCount: 45,
    rating: {
      average: 4.9,
      count: 289,
    },
    isFeatured: false,
    isTrending: true,
    isUpdated: true,
    isBookmarked: false,
    hasCTA: false,
  },
  {
    id: "9",
    slug: "studium-przypadku-wdrozenie-ksef-duza-firma",
    title: "Studium przypadku: Wdrożenie KSeF w firmie 500+ pracowników",
    excerpt: "Jak duża firma produkcyjna wdrożyła KSeF w 3 miesiące. Koszty, wyzwania i rezultaty.",
    thumbnail: "/large-factory-and-digital-transformation.jpg",
    category: "Studia",
    tags: ["studium przypadku", "duża firma", "wdrożenie"],
    difficulty: "Zaawansowany",
    contentType: "Artykuł",
    author: {
      name: "Michał Nowicki",
      avatar: "/professional-male-project-manager.png",
      role: "Project Manager",
      bio: "Kierownik projektów IT z 15-letnim doświadczeniem w dużych wdrożeniach.",
    },
    publishedAt: "2025-10-17T12:00:00Z",
    updatedAt: "2025-10-17T12:00:00Z",
    readingTime: 22,
    views: 3421,
    commentsCount: 9,
    rating: {
      average: 4.8,
      count: 54,
    },
    isFeatured: false,
    isTrending: false,
    isUpdated: false,
    isBookmarked: false,
    hasCTA: false,
  },
  {
    id: "10",
    slug: "ksef-bezpieczenstwo-danych-ochrona",
    title: "Bezpieczeństwo danych w KSeF - co musisz wiedzieć",
    excerpt: "Jak KSeF chroni Twoje dane? Szyfrowanie, RODO, certyfikaty bezpieczeństwa i najlepsze praktyki.",
    thumbnail: "/cybersecurity-and-data-protection.jpg",
    category: "Techniczne",
    tags: ["bezpieczeństwo", "RODO", "ochrona danych"],
    difficulty: "Średni",
    contentType: "Artykuł",
    author: {
      name: "Paweł Kamiński",
      avatar: "/professional-male-security-expert.jpg",
      role: "Ekspert Cyberbezpieczeństwa",
      bio: "Specjalista od bezpieczeństwa IT z certyfikatami CISSP i CEH.",
    },
    publishedAt: "2025-10-24T14:00:00Z",
    updatedAt: "2025-10-24T14:00:00Z",
    readingTime: 14,
    views: 4123,
    commentsCount: 17,
    rating: {
      average: 4.7,
      count: 68,
    },
    isFeatured: false,
    isTrending: false,
    isUpdated: false,
    isBookmarked: false,
    hasCTA: false,
  },
  {
    id: "11",
    slug: "ksef-harmonogram-wdrozenia-2026",
    title: "Harmonogram wdrożenia KSeF 2026 - krok po kroku",
    excerpt: "Szczegółowy plan wdrożenia z terminami, kamieniami milowymi i checklistą zadań.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    category: "Wdrożenie",
    tags: ["harmonogram", "plan", "terminy"],
    difficulty: "Podstawowy",
    contentType: "Checklist",
    author: {
      name: "Ewa Szymańska",
      avatar: "/placeholder.svg?height=100&width=100",
      role: "Koordynator Projektów",
      bio: "Ekspertka w zarządzaniu projektami wdrożeniowymi.",
    },
    publishedAt: "2025-10-16T11:00:00Z",
    updatedAt: "2025-10-26T13:00:00Z",
    readingTime: 11,
    views: 6789,
    commentsCount: 14,
    rating: {
      average: 4.8,
      count: 92,
    },
    isFeatured: false,
    isTrending: false,
    isUpdated: true,
    isBookmarked: false,
    hasCTA: true,
    ctaText: "Pobierz checklist",
    ctaAction: "download",
  },
  {
    id: "12",
    slug: "ksef-integracja-z-systemami-erp",
    title: "Integracja KSeF z systemami ERP - przewodnik",
    excerpt: "Jak zintegrować KSeF z SAP, Oracle, Microsoft Dynamics i innymi systemami ERP.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    category: "Techniczne",
    tags: ["integracja", "ERP", "SAP"],
    difficulty: "Zaawansowany",
    contentType: "Przewodnik",
    author: {
      name: "Krzysztof Wójcik",
      avatar: "/placeholder.svg?height=100&width=100",
      role: "Konsultant ERP",
      bio: "Specjalista od integracji systemów ERP z 12-letnim doświadczeniem.",
    },
    publishedAt: "2025-10-14T10:00:00Z",
    updatedAt: "2025-10-14T10:00:00Z",
    readingTime: 19,
    views: 3876,
    commentsCount: 22,
    rating: {
      average: 4.6,
      count: 61,
    },
    isFeatured: false,
    isTrending: false,
    isUpdated: false,
    isBookmarked: false,
    hasCTA: false,
  },
  {
    id: "13",
    slug: "ksef-zmiany-w-prawie-2026",
    title: "Zmiany w prawie podatkowym związane z KSeF",
    excerpt: "Przegląd wszystkich zmian legislacyjnych i ich wpływ na Twoją firmę.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    category: "Prawo",
    tags: ["prawo", "zmiany", "legislacja"],
    difficulty: "Średni",
    contentType: "Artykuł",
    author: {
      name: "Dr Anna Kowalska",
      avatar: "/placeholder.svg?height=100&width=100",
      role: "Doradca Podatkowy",
      bio: "Doradca podatkowy z 18-letnim doświadczeniem.",
    },
    publishedAt: "2025-10-12T09:00:00Z",
    updatedAt: "2025-10-27T11:00:00Z",
    readingTime: 16,
    views: 5234,
    commentsCount: 19,
    rating: {
      average: 4.7,
      count: 84,
    },
    isFeatured: false,
    isTrending: false,
    isUpdated: true,
    isBookmarked: false,
    hasCTA: false,
  },
  {
    id: "14",
    slug: "ksef-szkolenia-dla-pracownikow",
    title: "Jak przeszkolić pracowników do obsługi KSeF?",
    excerpt: "Kompleksowy program szkoleń, materiały edukacyjne i najlepsze praktyki.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    category: "Wdrożenie",
    tags: ["szkolenia", "pracownicy", "edukacja"],
    difficulty: "Podstawowy",
    contentType: "Przewodnik",
    author: {
      name: "Magdalena Krawczyk",
      avatar: "/placeholder.svg?height=100&width=100",
      role: "Trener Biznesowy",
      bio: "Trenerka z 10-letnim doświadczeniem w szkoleniach IT.",
    },
    publishedAt: "2025-10-13T14:00:00Z",
    updatedAt: "2025-10-13T14:00:00Z",
    readingTime: 13,
    views: 4567,
    commentsCount: 11,
    rating: {
      average: 4.8,
      count: 73,
    },
    isFeatured: false,
    isTrending: false,
    isUpdated: false,
    isBookmarked: false,
    hasCTA: true,
    ctaText: "Zobacz program",
    ctaAction: "training",
  },
  {
    id: "15",
    slug: "ksef-roi-zwrot-z-inwestycji",
    title: "ROI wdrożenia KSeF - kiedy się zwróci?",
    excerpt: "Analiza zwrotu z inwestycji w KSeF. Oszczędności, korzyści i realne przykłady.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    category: "Koszty",
    tags: ["ROI", "oszczędności", "korzyści"],
    difficulty: "Średni",
    contentType: "Artykuł",
    author: {
      name: "Robert Jankowski",
      avatar: "/placeholder.svg?height=100&width=100",
      role: "Analityk Finansowy",
      bio: "Specjalista od analizy ROI projektów IT.",
    },
    publishedAt: "2025-10-11T10:00:00Z",
    updatedAt: "2025-10-11T10:00:00Z",
    readingTime: 14,
    views: 6123,
    commentsCount: 16,
    rating: {
      average: 4.7,
      count: 89,
    },
    isFeatured: false,
    isTrending: false,
    isUpdated: false,
    isBookmarked: false,
    hasCTA: false,
  },
  {
    id: "16",
    slug: "ksef-dla-e-commerce",
    title: "KSeF dla sklepów internetowych - specyfika branży",
    excerpt: "Jak wdrożyć KSeF w e-commerce? Integracja z platformami, automatyzacja i najlepsze praktyki.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    category: "Wdrożenie",
    tags: ["e-commerce", "sklepy internetowe", "automatyzacja"],
    difficulty: "Średni",
    contentType: "Artykuł",
    author: {
      name: "Łukasz Mazur",
      avatar: "/placeholder.svg?height=100&width=100",
      role: "Ekspert E-commerce",
      bio: "Specjalista od automatyzacji procesów w e-commerce.",
    },
    publishedAt: "2025-10-09T12:00:00Z",
    updatedAt: "2025-10-09T12:00:00Z",
    readingTime: 15,
    views: 5678,
    commentsCount: 20,
    rating: {
      average: 4.8,
      count: 95,
    },
    isFeatured: false,
    isTrending: false,
    isUpdated: false,
    isBookmarked: false,
    hasCTA: false,
  },
  {
    id: "17",
    slug: "ksef-aktualnosci-pazdziernik-2025",
    title: "KSeF Aktualności - Październik 2025",
    excerpt: "Najważniejsze wiadomości, zmiany i aktualizacje dotyczące KSeF z ostatniego miesiąca.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    category: "Aktualności",
    tags: ["aktualności", "nowości", "zmiany"],
    difficulty: "Podstawowy",
    contentType: "Artykuł",
    author: {
      name: "Zespół KSeF Portal",
      avatar: "/placeholder.svg?height=100&width=100",
      role: "Redakcja",
      bio: "Zespół redakcyjny portalu KSeF.",
    },
    publishedAt: "2025-10-28T08:00:00Z",
    updatedAt: "2025-10-28T08:00:00Z",
    readingTime: 6,
    views: 8765,
    commentsCount: 13,
    rating: {
      average: 4.6,
      count: 102,
    },
    isFeatured: false,
    isTrending: true,
    isUpdated: false,
    isBookmarked: false,
    hasCTA: false,
  },
  {
    id: "18",
    slug: "ksef-infografika-proces-wdrozenia",
    title: "Infografika: Proces wdrożenia KSeF w 10 krokach",
    excerpt: "Wizualna reprezentacja całego procesu wdrożenia KSeF. Pobierz i wydrukuj!",
    thumbnail: "/placeholder.svg?height=400&width=600",
    category: "Wdrożenie",
    tags: ["infografika", "proces", "wizualizacja"],
    difficulty: "Podstawowy",
    contentType: "Infografika",
    author: {
      name: "Karolina Wojciechowska",
      avatar: "/placeholder.svg?height=100&width=100",
      role: "Graphic Designer",
      bio: "Projektantka infografik biznesowych.",
    },
    publishedAt: "2025-10-08T15:00:00Z",
    updatedAt: "2025-10-08T15:00:00Z",
    readingTime: 3,
    views: 9234,
    commentsCount: 8,
    rating: {
      average: 4.9,
      count: 124,
    },
    isFeatured: false,
    isTrending: false,
    isUpdated: false,
    isBookmarked: false,
    hasCTA: true,
    ctaText: "Pobierz PDF",
    ctaAction: "download",
  },
  {
    id: "19",
    slug: "ksef-video-tutorial-podstawy",
    title: "Video Tutorial: Podstawy KSeF w 15 minut",
    excerpt: "Kompleksowy video tutorial wyjaśniający podstawy KSeF. Idealne dla początkujących.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    category: "Podstawy",
    tags: ["video", "tutorial", "podstawy"],
    difficulty: "Podstawowy",
    contentType: "Video",
    author: {
      name: "Bartosz Kaczmarek",
      avatar: "/placeholder.svg?height=100&width=100",
      role: "Content Creator",
      bio: "Twórca treści edukacyjnych o tematyce biznesowej.",
    },
    publishedAt: "2025-10-07T10:00:00Z",
    updatedAt: "2025-10-07T10:00:00Z",
    readingTime: 15,
    views: 11234,
    commentsCount: 26,
    rating: {
      average: 4.9,
      count: 187,
    },
    isFeatured: false,
    isTrending: true,
    isUpdated: false,
    isBookmarked: false,
    hasCTA: true,
    ctaText: "Obejrzyj video",
    ctaAction: "video",
  },
  {
    id: "20",
    slug: "ksef-checklist-przed-wdrozeniem",
    title: "Checklist: Co sprawdzić przed wdrożeniem KSeF?",
    excerpt: "Kompletna lista kontrolna 50 punktów do sprawdzenia przed rozpoczęciem wdrożenia.",
    thumbnail: "/placeholder.svg?height=400&width=600",
    category: "Wdrożenie",
    tags: ["checklist", "przygotowanie", "lista kontrolna"],
    difficulty: "Podstawowy",
    contentType: "Checklist",
    author: {
      name: "Monika Piotrowska",
      avatar: "/placeholder.svg?height=100&width=100",
      role: "Konsultant Wdrożeniowy",
      bio: "Specjalistka od przygotowania firm do wdrożeń IT.",
    },
    publishedAt: "2025-10-06T09:00:00Z",
    updatedAt: "2025-10-25T14:00:00Z",
    readingTime: 9,
    views: 7456,
    commentsCount: 15,
    rating: {
      average: 4.8,
      count: 108,
    },
    isFeatured: false,
    isTrending: false,
    isUpdated: true,
    isBookmarked: false,
    hasCTA: true,
    ctaText: "Pobierz checklist",
    ctaAction: "download",
  },
]
